name: Frontend CI
on:
  push:
    branches: [master]
    paths:
      - "client/**"
  pull_request:
    branches: [master]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd client && npm install

      - name: Build React App
        run: cd client && npm run build
